# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e62b4d1b06ff5f403b4452d288184ffac440783b4d9fdd91f1ad346200af95b33087e188329f11c72764d032e667c8d5d1493e3b4b0e69dc1594fadc8282e75

test:
  secret_key_base: 211ab56f51f7f8c249edc57ced1d2eed47f242958fb129b55051ee33eee4350ef52c448baf195dfc8bf3a45b7972741ac3fcfab53453fe650effa730808eb7ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
